// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/emvi/hide"
)

type Client struct {
	ID       hide.ID    `json:"id"`
	Invoices []*Invoice `json:"invoices"`
}

func (Client) IsEntity() {}

type InvoiceInput struct {
	ClientID hide.ID          `json:"clientID"`
	Items    []*LineItemInput `json:"items"`
}

type LineItemInput struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	UnitCost    float64  `json:"unitCost"`
	TaxRate     *float64 `json:"taxRate"`
	Quantity    float64  `json:"quantity"`
}

type PreviewInvoiceInput struct {
	Number   int64            `json:"number"`
	ClientID hide.ID          `json:"clientID"`
	Items    []*LineItemInput `json:"items"`
}

type User struct {
	ID hide.ID `json:"id"`
}

func (User) IsEntity() {}
