trigger:
  branches:
    include:
      - "*"

pr:
  branches:
    include:
      - "*"

resources:
  - repo: self

variables:
  tag: "$(Build.BuildNumber)"
  repository: "kiwisheets/invoicing"
  isMain: $[in(variables['Build.SourceBranch'], 'refs/heads/main')]

stages:
  - stage: Test
    displayName: Test
    jobs:
      - job: Test
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: Go@0
            displayName: Run Golang Tests
            inputs:
              command: test

  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - bash: echo "$(tag)"

          - task: Docker@2
            displayName: Build an image
            inputs:
              repository: "$(repository)"
              command: "build"
              Dockerfile: "**/Dockerfile"
              tags: "$(tag)"

          - task: Docker@2
            displayName: Push image
            condition: and(succeeded(), eq(variables.isMain, true))
            inputs:
              containerRegistry: "Docker"
              repository: "$(repository)"
              command: "push"
              tags: "$(tag)"
