version: "3"
services:
  redis:
    image: redis:latest
    ports:
      - "6380:6379"

  postgres:
    image: postgres:latest
    # command config set up from pgtune -
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=768MB"
      - "-c"
      - "effective_cache_size=2304MB"
      - "-c"
      - "maintenance_work_mem=192MB"
      - "-c"
      - "checkpoint_completion_target=0.7"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=100"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_io_concurrency=200"
      - "-c"
      - "work_mem=3932kB"
      - "-c"
      - "min_wal_size=1GB"
      - "-c"
      - "max_wal_size=4GB"
    environment:
      PGDATA: /var/lib/postgresql/data/db
      POSTGRES_DB: invoice
      POSTGRES_USER: dts
      POSTGRES_PASSWORD: password
    volumes:
      - pg-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 3072M

volumes:
  pg-db:
